name: Save New Order

on:
  workflow_dispatch:  # Ручной запуск
  repository_dispatch:
    types: [new_order_event]

jobs:
  process-order:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Даем права на запись
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Process Order
      env:
        ORDER_JSON: '${{ toJson(github.event.client_payload) }}'
      run: |
        # Создаем Node.js скрипт для обработки заказа
        cat > process_order.js << 'EOF'
        const fs = require('fs');
        const path = require('path');
        
        try {
          // Получаем данные заказа
          const orderData = JSON.parse(process.env.ORDER_JSON || '{}');
          
          console.log('📦 Получен заказ:', orderData.orderNumber);
          
          // Путь к файлу заказов
          const ordersPath = path.join(__dirname, 'orders.json');
          
          // Читаем существующие заказы
          let orders = [];
          if (fs.existsSync(ordersPath)) {
            const content = fs.readFileSync(ordersPath, 'utf8');
            orders = JSON.parse(content || '[]');
            if (!Array.isArray(orders)) {
              orders = [];
            }
          }
          
          // Создаем полный объект заказа
          const fullOrder = {
            id: 'order_' + Date.now() + '_' + Math.random().toString(36).substr(2, 9),
            ...orderData,
            savedAt: new Date().toISOString(),
            status: 'pending',
            workflowRun: process.env.GITHUB_RUN_ID || 'manual'
          };
          
          // Добавляем в начало
          orders.unshift(fullOrder);
          
          // Ограничиваем до 1000 заказов
          if (orders.length > 1000) {
            orders = orders.slice(0, 1000);
          }
          
          // Сохраняем
          fs.writeFileSync(ordersPath, JSON.stringify(orders, null, 2));
          
          console.log('✅ Заказ сохранен!');
          console.log(`📊 Всего заказов: ${orders.length}`);
          console.log(`🆔 Номер: ${orderData.orderNumber}`);
          console.log(`💰 Сумма: ${orderData.total} руб.`);
          
          // Возвращаем результат
          process.stdout.write(JSON.stringify({
            success: true,
            message: 'Order saved successfully',
            orderId: fullOrder.id,
            totalOrders: orders.length
          }));
          
        } catch (error) {
          console.error('❌ Ошибка:', error);
          process.stdout.write(JSON.stringify({
            success: false,
            error: error.message
          }));
          process.exit(1);
        }
        EOF
        
        # Запускаем скрипт
        node process_order.js
        
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        
        git add orders.json
        git commit -m "📦 Добавлен заказ ${{ github.event.client_payload.orderNumber || 'Новый заказ' }}"
        git push
